### PR TITLE
show spinner when query request is in progess.

### PR DESCRIPTION
**Pull request by ebraheemijaz**

### CODE REVIEW

**Review by awaisraad — APPROVED** [review]

**Comment by bradtraversy** [comment]
The spinner is displayed because the state is set to true by default. Shouldn't be a need to set to true manually

**Comment by ebraheemijaz** [comment]
yes, you are right, but let me explain in detail maybe I'm not clear previously
1- spinner is set to true by default
2- once API request(all characters) is finished, the spinner is set to false
3- now when the user enters text (e.g 'wal') to search field,  again an API request(query i.e 'wal') will be sent to the backend, but this time spinner is set to false.
my suggestion:
1- when the user enter text(e.g 'wal') to search box,
2- spinner is set to true
3- API request(query i.e 'wal') will be sent 
4- when the response comes back from a backend
5- set spinner to false and then render

**Comment by bradtraversy** [comment]
You're right, didn't even realize lol

**Comment by ebraheemijaz** [comment]
my first ever contribution to any project got accepted. so happy right now =D

**Pull request merged**
